### PR TITLE
Add hash location routing to let user refreshing the browser on the same page

### PR DESCRIPTION
**Pull request by R0muald**
- add `#/` part in the URL

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for the contribution, but before merging I would like to know in which case the default path strategy does not work well for you?

The default Angular strategy (without the hash) is based on the standard HTML5 pushState API, now supported on all modern browsers except for IE9. Even though Angular 2+ works on IE9, the performance will greatly suffer on this browser.

**Comment by R0muald** [comment]
The problem I was facing is, if I'm on the `About` page and refresh the browser URL, then the app come back blank since that page does not actually exist in the app context. If we don't have the hash, I'm not sure if we can bookmark pages when needed.

**Comment by sinedied** [comment]
I tried to reproduce your problem in Chrome, Safari and Firefox by directly acceding to the `http://localhost:4200/about` url and then hit F5 and it to worked.
Did you tried using the webpack server or using a real server?

It seems that this issue is mainly a server-side issue, as the server should support HTML5 routing (aka URL rewriting), see also for reference: https://github.com/angular/angular/issues/4735 

According to the Angular team, unless for specific needs HTML5 routing should be used to allow for cleaner URLs and also enable server-side rendering for specific pages if needed: https://angular.io/docs/ts/latest/guide/router.html#!#browser-url-styles

Still, I'm divided on what would be the best approach for this:

- merge this PR and add a note to the docs explaining why and how to enable HTML5 routing with the potential issues on the server (I'm leaning on this one)

- follow the Angular team recommendation and keep HTML5 routing as the default and add a note on the docs on the potential server issues

I would like to keep this SK as close to the recommendations as possible, but being frustration-free out of the box is also important, any thoughts? @japf, @creal73, @ludovicderochethales, @gaetanmaisse ?

**Comment by R0muald** [comment]
OK, after doing more test, I do actually have on dev env the app working correctly this html5 mode. But once I build it, I use `http-server ./dist` to run it locally, this is where I got the blank page when hitting F5. So probably related to `http-server` at this point...

**Comment by ludovicderochethales** [comment]
In my opinion it's better to follow Angular team recommendation. We can add
a note in documentation to explain how to enable "#".

Le lun. 13 févr. 2017 à 19:11, Yohan Lasorsa <notifications@github.com> a
écrit :

**Comment by creal73** [comment]
I agree with @ludovicderochethales. 

After reading [this comment](https://github.com/angular/angular/issues/4735#issuecomment-214628830). I prefer stay close to official recommendations.

**Comment by sinedied** [comment]
@R0muald maybe you could try [lite-server](https://www.npmjs.com/package/lite-server) as a replacement for `http-server`? Also, if it's just for testing you can use `npm start -- --prod`, maybe it's also a good idea to add a `serve:dist` npm task.

@creal73 good point, and it also seems that the *hashbang* mode also cause issues with real anchor links, indexation (Google has now deprecated the hash "hack" for its crawlers) and caching.

Then for now it's best to keep with angular defaults, I'll create a separate issue to add a doc on this. We can also add a choice between HTML5 path or hashbang routing when we'll move to a Yeoman generator.

**Comment by creal73** [comment]
@sinedied strategy seems good to me.

**Comment by R0muald** [comment]
Thank you for all those great feedback. 
After reading more about best practices and some other server-side rendering (universal) posts, keeping HTML5 path will make it easier for future update of the architecture.
I will close the pull request.
Thanks!

**Pull request closed without merging**
